name: Unity - Build
on: 
  workflow_dispatch:
  push:
    branches:
    - stable

jobs:
  build:
    # Build a win64 build and add it to a release using the latest tag's major and minor version and the amount of commits since the last major or minor version increment as the patch version
    name: Build project
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout repository
        id: checkout
        uses: actions/checkout@v3
        with:
          ref: stable
          fetch-depth: 0
        
      - name: Cache repository
        id: cache
        uses: actions/cache@v2
        with:
          path: Library
          key: Library-${{ hashFiles('Assets/**', 'Packages/**', 'ProjectSettings/**') }}
          restore-keys: |
            Library-
      
      - name: Generate Semantic Version
        id: version
        uses: paulhatch/semantic-version@v4.0.3
        with:
          tag_prefix: ''
          format: "${major}.${minor}.${increment}"
          bump_each_commit: true
      
      - name: Build project
        id: build
        uses: game-ci/unity-builder@v2.1.0
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          targetPlatform: StandaloneWindows64
          customParameters: -Development
          buildName: Accession
          versioning: Custom
          version: ${{ steps.version.outputs.version_tag }}
          
      - name: Archive build
        id: archive
        uses: thedoctor0/zip-release@main
        with:
          type: zip
          filename: ../../Accession-${{ steps.version.outputs.version_tag }}-win64.zip
          directory: build/StandaloneWindows64/
          
      - name: Create release
        id: release
        uses: softprops/action-gh-release@v1
        with:
          name: ${{ steps.version.outputs.version_tag }}
          tag_name: ${{ steps.version.outputs.version_tag }}
          prerelease: true
          files: Accession-${{ steps.version.outputs.version_tag }}-win64.zip
